FAQs
==========================================================================================
导入数据
---------------------------------------------------------------------------
导入数据时提示::

        feats.append(ft.tranform(row.tobytes()))
        raise VseError(rt, b'input feature invalid')
        vsepy.VseError: <exception str() failed>

原因：输入的原生向量数组数据长度和向量库需要的不匹配。

解决方法：检查输入的向量数组数据长度与向量库的数据长度，并保证长度一致。
